### ISSUE TITLE
SovaSlava - Trader could spend more tokens/eth, than planned - need slippage protection

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-splits-judging#53]
SovaSlava

medium

# Trader could spend more tokens/eth, than planned - need slippage protection

## Summary
if  trader's tx **in pending status for a long time**, exchange rate(twap) will change greatly(**if twap is short period**), and **pool has low liquidity,** so amount of beneficiary tokens could be more, than trader calculated, when he sent tx. Because trader could not set maxAmountDefaultToken value, as on defi exchanges, like uniswap.
## Vulnerability Detail
Case:
* Beneficiary token - DAI. 
* TWAP - 10 minutes. 
*Someone sent tokens (example name - tkn) to contract, and uniswap v3 pair has small reserves in tkn/dai.
* Trader look at exchange rate: 100 tkn/1 dai. Its ok for him.
* Trader send tx(with low gas price) -> flash({base=tknTokenAddress, baseAmount=100, quote=daiTokenAddress})
* ...some hours later, miners mine this tx and in this hours someone made exchange with big amount in uniswap v3 in pair tkn/dai -> price changed and twap too -> 80 tkn/1 dai. (big change of rate, because pool has low reserves)
* swapperImpl send request to uniswap v3 oracle and get twap, which is very different from what trader saw, when he sent tx.
* Trader gets 100 tkn, but swapper contract transferFrom trader more, than trader planned. Yes, hi has enough tokens, but its bad surprice for him.
## Impact
Trader give more tokens, than hi planned. 
## Code Snippet
https://github.com/sherlock-audit/2023-04-splits/blob/main/splits-swapper/src/SwapperImpl.sol#L273
## Tool used
Manual Review
## Recommendation
Give opportunity for trader pass maxTransferFrom value in parameters in flash function. 

Duplicate of #37

**Comment by SovaSlava** [comment]
Escalate for 10 USDC

I think this issue is valid.  

Quote from sherlock rules:
> List of Issue categories that are considered valid:
Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high

Detail explanation of issue:
**The main problem is, that trader can specify only incoming amount, but can not specify amount, which will be transfered from his balance. And can not set deadline of execution tx.**

1. Trader call flash()
```solidity
  function flash(OracleImpl.QuoteParams[] calldata quoteParams_, bytes calldata callbackData_)
        external
        payable
        pausable
    {
        address _tokenToBeneficiary = $tokenToBeneficiary;
        (uint256 amountToBeneficiary, uint256[] memory amountsToBeneficiary) =
            _transferToTrader(_tokenToBeneficiary, quoteParams_);

```
as we can see, amount of tokens (which wil be transfered from trader to beneficiary) is getting from internal function  _transferToTrader
```solidity

  function _transferToTrader(address tokenToBeneficiary_, OracleImpl.QuoteParams[] calldata quoteParams_)
        internal
        returns (uint256 amountToBeneficiary, uint256[] memory amountsToBeneficiary)
    {
        amountsToBeneficiary = $oracle.getQuoteAmounts(quoteParams_);
```
this amount gets from oracle(uniswap v3). 

Trader send to flash function  - OracleImpl.QuoteParams[] calldata quoteParams_
```solidity
   struct QuoteParams {
        QuotePair quotePair;
        uint128 baseAmount;
        bytes data;
    }

struct QuotePair {
    address base;
    address quote;
}
```

Trader can specify only baseAmount.. this amount he will get, but he can not specify how much will be trasfer  from his balance. 

The trader's transaction can be pending in mempool for a long time. Without deadline check, the trade transaction can be executed in a long time after the trader submit the transaction, at that time, the function execution can be done in a sub-optimal price, which increase amount, which transfer from trader.

Splits contract use TWAP, but it could be set as very short period. Plus, pool could have low liquidity of tokens.

So, amount of beneficiary tokens could increase and be more, than trader calculated, when send tx. Trader could not specify deadline timestamp of execution tx or max amount, which wil be transfered from his wallet, like on most exchanges.

The deadline check ensure that the transaction can be executed on time and the expired transaction revert.

Test case:

Beneficiary token - DAI.
TWAP - 10 minutes.
*Someone sent tokens (example name - tkn) to contract, and uniswap v3 pair has small reserves in tkn/dai.
Trader look at exchange rate: 100 tkn/1 dai. Its ok for him.
* Trader send tx(with low gas price) -> flash({base=tknTokenAddress, baseAmount=100, quote=daiTokenAddress})
* Some hours later, miners mine this tx and in this hours, but price has changed and twap too -> 80 tkn/1 dai. (big change of rate, because pool has low reserves).
*  swapperImpl.sol send request to uniswap v3 oracle and get twap, which is very different from what trader saw, when he sent tx.
Trader gets 100 tkn, but swapper contract transferFrom trader more, than trader planned. 





I recommend the protocol add deadline check and add slippage control.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I think this issue is valid.  
> 
> Quote from sherlock rules:
> > List of Issue categories that are considered valid:
> Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high
> 
> Detail explanation of issue:
> **The main problem is, that trader can specify only incoming amount, but can not specify amount, which will be transfered from his balance. And can not set deadline of execution tx.**
> 
> 1. Trader call flash()
> ```solidity
>   function flash(OracleImpl.QuoteParams[] calldata quoteParams_, bytes calldata callbackData_)
>         external
>         payable
>         pausable
>     {
>         address _tokenToBeneficiary = $tokenToBeneficiary;
>         (uint256 amountToBeneficiary, uint256[] memory amountsToBeneficiary) =
>             _transferToTrader(_tokenToBeneficiary, quoteParams_);
> 
> ```
> as we can see, amount of tokens (which wil be transfered from trader to beneficiary) is getting from internal function  _transferToTrader
> ```solidity
> 
>   function _transferToTrader(address tokenToBeneficiary_, OracleImpl.QuoteParams[] calldata quoteParams_)
>         internal
>         returns (uint256 amountToBeneficiary, uint256[] memory amountsToBeneficiary)
>     {
>         amountsToBeneficiary = $oracle.getQuoteAmounts(quoteParams_);
> ```
> this amount gets from oracle(uniswap v3). 
> 
> Trader send to flash function  - OracleImpl.QuoteParams[] calldata quoteParams_
> ```solidity
>    struct QuoteParams {
>         QuotePair quotePair;
>         uint128 baseAmount;
>         bytes data;
>     }
> 
> struct QuotePair {
>     address base;
>     address quote;
> }
> ```
> 
> Trader can specify only baseAmount.. this amount he will get, but he can not specify how much will be trasfer  from his balance. 
> 
> The trader's transaction can be pending in mempool for a long time. Without deadline check, the trade transaction can be executed in a long time after the trader submit the transaction, at that time, the function execution can be done in a sub-optimal price, which increase amount, which transfer from trader.
> 
> Splits contract use TWAP, but it could be set as very short period. Plus, pool could have low liquidity of tokens.
> 
> So, amount of beneficiary tokens could increase and be more, than trader calculated, when send tx. Trader could not specify deadline timestamp of execution tx or max amount, which wil be transfered from his wallet, like on most exchanges.
> 
> The deadline check ensure that the transaction can be executed on time and the expired transaction revert.
> 
> Test case:
> 
> Beneficiary token - DAI.
> TWAP - 10 minutes.
> *Someone sent tokens (example name - tkn) to contract, and uniswap v3 pair has small reserves in tkn/dai.
> Trader look at exchange rate: 100 tkn/1 dai. Its ok for him.
> * Trader send tx(with low gas price) -> flash({base=tknTokenAddress, baseAmount=100, quote=daiTokenAddress})
> * Some hours later, miners mine this tx and in this hours, but price has changed and twap too -> 80 tkn/1 dai. (big change of rate, because pool has low reserves).
> *  swapperImpl.sol send request to uniswap v3 oracle and get twap, which is very different from what trader saw, when he sent tx.
> Trader gets 100 tkn, but swapper contract transferFrom trader more, than trader planned. 
> 
> 
> 
> 
> 
> I recommend the protocol add deadline check and add slippage control.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Please note swapper#flash callers are expected to be sophisticated. 
Lead Watson comment:
> Bots are expected to be sophisticated. They can self-own in many ways, but the expectation is that they could cancel tx if they don’t want it lingering, or would push through a new tx to execute the trade.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Please note swapper#flash callers are expected to be sophisticated. 
> Lead Watson comment:
> > Bots are expected to be sophisticated. They can self-own in many ways, but the expectation is that they could cancel tx if they don’t want it lingering, or would push through a new tx to execute the trade.

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
